In [30]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [31]:
df=pd.read_csv('/content/Iris.csv')
print('shape',df.shape)
df.head()

shape (150, 6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [33]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [34]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df.drop('Id', axis=1, inplace=True)

In [37]:
x=df.drop(['Species'],axis=1)
y=df['Species']

In [38]:
x.shape

(150, 4)

In [39]:
y.shape

(150,)

In [40]:
x.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [41]:
#one-hot encoding
onehot_df=pd.get_dummies(y)
onehot_df.head()

   Iris-setosa  Iris-versicolor  Iris-virginica
0         True            False           False
1         True            False           False
2         True            False           False
3         True            False           False
4         True            False           False

In [42]:
onehot_df.shape

(150, 3)

In [43]:
onehot_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Iris-setosa      150 non-null    bool
 1   Iris-versicolor  150 non-null    bool
 2   Iris-virginica   150 non-null    bool
dtypes: bool(3)
memory usage: 582.0 bytes

In [44]:
#Label encoding
#Apply Label Encoding on the species column
label_df=y.copy()
le=LabelEncoder()
categorical_cols=y
label_df=le.fit_transform(y)

In [45]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [46]:
#train-test split
x_train,x_test,y_train,y_test=train_test_split(x,label_df,test_size=0.2,random_state=42,stratify=label_df)

In [47]:
x_train.head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
8              4.4           2.9            1.4           0.2
106            4.9           2.5            4.5           1.7
76             6.8           2.8            4.8           1.4
9              4.9           3.1            1.5           0.1
89             5.5           2.5            4.0           1.3

In [48]:
#wihtout scaling
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)

0.9666666666666667

In [49]:
#Prepare two copies of dataframe. Apply Feature scaling (Standardization and
#Normalization on two separate dataframes)
scaler= StandardScaler()
cols_to_scale=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
#fitting on training data
x_train[cols_to_scale]=scaler.fit_transform(x_train[cols_to_scale])
#applying same transformations on test data
x_test[cols_to_scale]=scaler.transform(x_test[cols_to_scale])

In [51]:
x_train#scaled

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
8        -1.721568     -0.324840      -1.347036     -1.320168
106      -1.124492     -1.226129       0.414290      0.651867
76        1.144395     -0.550162       0.584741      0.257460
9        -1.124492      0.125805      -1.290219     -1.451638
89       -0.408002     -1.226129       0.130206      0.125991
..             ...           ...            ...           ...
37       -1.124492      0.125805      -1.290219     -1.451638
2        -1.363322      0.351127      -1.403853     -1.320168
33       -0.408002      2.604352      -1.347036     -1.320168
52        1.263810      0.125805       0.641558      0.388929
3        -1.482738      0.125805      -1.290219     -1.320168

[120 rows x 4 columns]

In [52]:
#scaled
model1=LogisticRegression()
model1.fit(x_train,y_train)
y_pred1=model1.predict(x_test)
accuracy_score(y_test,y_pred1)

0.9333333333333333

In [54]:

minmax= MinMaxScaler()
cols_to_scale=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']
#fitting on training data
x_train_minmax=x_train.copy()
x_test_minmax=x_test.copy()
x_train_minmax[cols_to_scale]=minmax.fit_transform(x_train[cols_to_scale])
#applying same transformations on test data
x_test_minmax[cols_to_scale]=minmax.transform(x_test[cols_to_scale])

In [55]:
x_train_minmax#minmax scaled

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
8         0.027778      0.375000       0.051724      0.041667
106       0.166667      0.208333       0.586207      0.666667
76        0.694444      0.333333       0.637931      0.541667
9         0.166667      0.458333       0.068966      0.000000
89        0.333333      0.208333       0.500000      0.500000
..             ...           ...            ...           ...
37        0.166667      0.458333       0.068966      0.000000
2         0.111111      0.500000       0.034483      0.041667
33        0.333333      0.916667       0.051724      0.041667
52        0.722222      0.458333       0.655172      0.583333
3         0.083333      0.458333       0.068966      0.041667

[120 rows x 4 columns]

In [56]:
#minmax scaling
model2=LogisticRegression()
model2.fit(x_train_minmax,y_train)
y_pred2=model2.predict(x_test_minmax)
accuracy_score(y_test,y_pred2)

0.9