In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('/content/indian_ecommerce_orders.csv')

In [ ]:
df.head()

,OrderID,UserID,Product,Category,Quantity,OrderAmount,DiscountPercent,ShippingFee,OrderDate,PaymentMethod,Channel,City,State,Pincode,Gender,CustomerRating,Returned,DeliveryDays
0,ORD6578753,U895591,Webcam 1080p,Gaming,zero,4676.75,38.7,24.86,2023-03-14 19:52:00,NetBanking,Marketplace,Kolkata,DL,159203,Other,five,NaN,9
1,ORD4208526,U850646,Fitness Tracker,Smart Home,3,NaN,15.1,44.6,18/01/2023 07:39 PM,COD,Mobile App,Mumbai,DL,220792,F,five,False,NaN
2,ORD6623360,U306577,1251 Phone Case\n1251 Phone Case\nName:...,Smart Home,5,NaN,ten%,84.29,03-23-2023,"1251 cod\n1251 cod\nname: paymentmethod,...",Website,Ahmedabad,MH,652701,F,five,False,3
3,ORD8547397,U574029,Power Bank,Gaming,2,2092.74,33.1,138.4,02-26-2023,UPI,Website,Bengaluru,GJ,269727,F,4,True,3
4,ORD1443630,U680742,Laptop Stand,Smart Home,3,4617.4,19.2,247.19,2023-06-30 16:55:00,Card,Website,Kolkata,TN,NaN,Other,2,True,7

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1960 entries, 0 to 1959
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1960 non-null   object
 1   UserID           1960 non-null   object
 2   Product          1960 non-null   object
 3   Category         1960 non-null   object
 4   Quantity         1909 non-null   object
 5   OrderAmount      1809 non-null   object
 6   DiscountPercent  1794 non-null   object
 7   ShippingFee      1832 non-null   object
 8   OrderDate        1960 non-null   object
 9   PaymentMethod    1960 non-null   object
 10  Channel          1960 non-null   object
 11  City             1960 non-null   object
 12  State            1960 non-null   object
 13  Pincode          1620 non-null   object
 14  Gender           1477 non-null   object
 15  CustomerRating   1772 non-null   object
 16  Returned         1849 non-null   object
 17  DeliveryDays     1836 non-null   object
dtypes: object(18)
memory usage: 275.8+ KB

In [ ]:
df.describe()

,OrderID,UserID,Product,Category,Quantity,OrderAmount,DiscountPercent,ShippingFee,OrderDate,PaymentMethod,Channel,City,State,Pincode,Gender,CustomerRating,Returned,DeliveryDays
count,1960,1960,1960,1960,1909,1809,1794,1832,1960,1960,1960,1960,1960,1620,1477,1772,1849,1836
unique,1400,1399,83,5,10,1228,381,1160,1208,35,3,51,8,1107,3,6,2,10
top,ORD3981450,U382619,Fitness Tracker,Home Office,3,free,ten%,free,01-15-2023,Card,Mobile App,Mumbai,DL,4000A,M,4,False,two
freq,5,5,103,415,372,92,156,169,11,383,680,238,298,73,503,371,977,217

In [ ]:
df.duplicated().sum()

np.int64(353)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Quantity'] = df['Quantity'].replace({'zero':0})
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [ ]:
df['CustomerRating'] = df['CustomerRating'].replace({'one':1,'two':2,'three':3,'four':4,'five':5})
df['CustomerRating'] = pd.to_numeric(df['CustomerRating'], errors='coerce')

In [ ]:
df['DiscountPercent'] = df['DiscountPercent'].replace({'ten%':10})
df['DiscountPercent'] = df['DiscountPercent'].str.replace('%','')
df['DiscountPercent'] = pd.to_numeric(df['DiscountPercent'], errors='coerce')

In [ ]:
df['OrderAmount'] = pd.to_numeric(df['OrderAmount'], errors='coerce')
df['ShippingFee'] = pd.to_numeric(df['ShippingFee'], errors='coerce')
df['DeliveryDays'] = pd.to_numeric(df['DeliveryDays'], errors='coerce')

In [ ]:
df['OrderDate'] = pd.to_datetime(df['OrderDate'], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1607 entries, 0 to 1959
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1607 non-null   object
 1   UserID           1607 non-null   object
 2   Product          1607 non-null   object
 3   Category         1607 non-null   object
 4   Quantity         1563 non-null   float64
 5   OrderAmount      1341 non-null   float64
 6   DiscountPercent  1333 non-null   float64
 7   ShippingFee      1359 non-null   float64
 8   OrderDate        557 non-null    datetime64[ns]
 9   PaymentMethod    1607 non-null   object
 10  Channel          1607 non-null   object
 11  City             1607 non-null   object
 12  State            1607 non-null   object
 13  Pincode          1331 non-null   object
 14  Gender           1210 non-null   object
 15  CustomerRating   1451 non-null   float64
 16  Returned         1512 non-null   object
 17  DeliveryDays     1329 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(11)
memory usage: 238.5+ KB

In [ ]:
df.isnull().sum()

OrderID               0
UserID                0
Product               0
Category              0
Quantity             44
OrderAmount         266
DiscountPercent     274
ShippingFee         248
OrderDate          1050
PaymentMethod         0
Channel               0
City                  0
State                 0
Pincode             276
Gender              397
CustomerRating      156
Returned             95
DeliveryDays        278
dtype: int64

In [ ]:
df.dropna(subset=['CustomerRating'], inplace=True)

In [ ]:
numarical_cols=df.select_dtypes(include=['int64','float64']).columns
catecorical_cols=df.select_dtypes(include=['object','category']).columns
print('Numerical_cols:',list(numarical_cols))
print('catecorical_cols:',list(catecorical_cols))

Numerical_cols: ['Quantity', 'OrderAmount', 'DiscountPercent', 'ShippingFee', 'CustomerRating', 'DeliveryDays']
catecorical_cols: ['OrderID', 'UserID', 'Product', 'Category', 'PaymentMethod', 'Channel', 'City', 'State', 'Pincode', 'Gender', 'Returned']

In [ ]:
df['Quantity']=df['Quantity'].fillna(df['Quantity'].mean())
df['OrderAmount']=df['OrderAmount'].fillna(df['OrderAmount'].mean())
df['DiscountPercent']=df['DiscountPercent'].fillna(df['DiscountPercent'].mean())
df['ShippingFee']=df['ShippingFee'].fillna(df['ShippingFee'].mean())
df['DeliveryDays']=df['DeliveryDays'].fillna(df['DeliveryDays'].mean())
df['OrderDate']=df['OrderDate'].fillna(df['OrderDate'].mean())

In [ ]:
df['Pincode']=df['Pincode'].fillna(df['Pincode'].mode()[0])
df['Gender']=df['Gender'].fillna(df['Gender'].mode()[0])
df['Returned']=df['Returned'].fillna(df['Returned'].mode()[0])

/tmp/ipython-input-1134096440.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Returned']=df['Returned'].fillna(df['Returned'].mode()[0])

In [ ]:
df.isnull().sum()

OrderID            0
UserID             0
Product            0
Category           0
Quantity           0
OrderAmount        0
DiscountPercent    0
ShippingFee        0
OrderDate          0
PaymentMethod      0
Channel            0
City               0
State              0
Pincode            0
Gender             0
CustomerRating     0
Returned           0
DeliveryDays       0
dtype: int64